[project]
name = "10min10newsstatic"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "GaganABajaj", email = "gagbajaj5@gmail.com" }
]
requires-python = ">=3.12"
dependencies = []

[project.scripts]
10min10newsstatic = "10min10newsstatic:main"

[build-system]
requires = ["uv_build>=0.12.6,<0.13.0"]
build-backend = "uv_build"
